language: node_js
dist: trusty
sudo: required
node_js: node

env:
  - LOGGER_LEVEL='INFO'

before_install:
  - $TRAVIS_BUILD_DIR/bin/bxsetup.sh

install:
  - cd $TRAVIS_BUILD_DIR/libs/deployer && npm install
  - cd $TRAVIS_BUILD_DIR/libs/deployer/plugins/actions/combinator && npm install
  - cd $TRAVIS_BUILD_DIR/libs/ && ./link.sh

script:
  - $TRAVIS_BUILD_DIR/bin/runtests.sh
